config/routes.rb
Csps::Application.routes.draw do
  resource :session, controller: 'session' do
    get :welcome, :restore
  end
  resource :syncs
  resources :zones
  resources :users do
    get :logins, on: :member, to: :user_logins
    get :logins, :password, on: :collection
  end
  resources :queries do
    get :export, on: :member
  end

  resources :illnesses do
    post :classification, on: :member
  end

  resources :children do
    collection do
      get :calculations, :questionnaire
      post :temp
    end
    member do
      get :indices
    end
    resources :diagnostics do
      collection do
        get :questionnaire
      end
      member do
        get :treatments, :wait
        post :calculations
      end
    end
  end

  root to: 'children#index'
end

app/controllers/children_controller.rb
require 'stringio'
require 'base64'

class ChildrenController < ApplicationController
  login_required
  fetch 'Child', :also => :indices
  helper Ziya::HtmlHelpers::Charts
  helper Wopata::Ziya::HtmlHelpersFix

  class Search < Struct.new(:name, :mother, :born_on, :village_id, :identifier)
    def to_params_hash
      @hash ||= {}.tap do |h|
        h[:name] = name if name.present?
        h[:mother] = mother if mother.present?
        h[:born] = born_on if born_on.present?
        h[:village] = village_id if village_id.present?
        h[:identifier] = identifier if identifier.present?
      end
    end
  end

  before_filter :rewrite_photo, only: [:update, :temp]

  def index
    # Clean empty children (only photo)
    Child.unfilled.destroy_all

    @q = Search.from_hash params
    @orig_name = @q.name.dup if @q.name

    if params[:o].blank?
      order = 'last_visit_at'
      params[:d] = 'd'
    elsif params[:o] == 'zone'
      order = 'zones.name, children.village_name'
    else
      order = params[:o]
    end

    @children =
      begin
        model.search(@q, order, params[:d])
      rescue => e
        @error = e.message
        []
      end

    @page = (params[:page] || '1').to_i
  end

  def calculations
    data = params[:d]
    weight = data[:weight].to_f
    height = data[:height].to_f
    days = data[:days].to_f
    gender = (data[:gender] == 'true')
    render json: {
      weight_age: [
        *Diagnostic.scores('weight_age', gender, days, weight, height),
        Index::WARNING['weight_age'], Index::ALERT['weight_age']],
      height_age: [
        *Diagnostic.scores('height_age', gender, days, weight, height),
        Index::WARNING['height_age'], Index::ALERT['height_age']],
      weight_height: [
        *Diagnostic.scores('weight_height', gender, days, weight, height),
        Index::WARNING['weight_height'], Index::ALERT['weight_height']] }
  end

  def indices
    name = params[:name]
    diag = Diagnostic.find(params[:diagnostic]) if params[:diagnostic].present?
    if diag
      v, i = diag.index name
    else
      v, i = @child.index name
    end
    curve = Index.where(:name => Index::NAMES.index(name.gsub('_', '-'))).gender(@child.gender).age_in_months(@child.months).order(:x).all
    chart = Ziya::Charts::Line.new
    chart.add :theme, 'pimp'
    labels = if name == 'weight_height'
      curve.map(&:x).map {|e| ((e%6)==0 ? e : '')}
    else
      curve.map(&:x).map {|e| ((e%200)==0 ? (e/30).round : '')}
    end
    chart.add :axis_category_text, labels
    chart.add(:series, '', curve.map do |c|
      {:value => c.y}
    end)
    chart.add(:series, '', curve.map do |c|
      {:value => c.sd3neg}
    end)
    chart.add(:series, '', curve.map do |c|
      {:value => c.sd3}
    end)
    chart.add(:series, '', curve.map do |c|
      if c == i
        {:value => v,
         :note => @child.name,
         :note_x => (i.x > (curve.last.x / 2) ? -15 : 15),
         :note_y => (v > (curve.last.y / 2) ? 30 : -30),
         :tooltip => v}
      else
        {}
      end
    end)
    render xml: chart.to_xml
  end

  def show
    back 'Liste des patients', children_path
  end

  def new
    return see_other(children_path) unless Zone.csps.point?
    @child = Child.new
    @diagnostic = @child.diagnostics.build # Cannot be prebuilt here!
    back 'Liste des patients', children_path
  end

  def questionnaire
    @child = Child.new born_on: params[:born_on]
    @diagnostic = @child.diagnostics.build_with_answers
    render layout: false
  end

  def create
    return see_other(children_path) unless Zone.csps.point?

    diag = params[:child].delete(:diagnostic)
    answers = diag.delete(:sign_answers).values

    @child = Child.temporary.first || Child.new
    @child.attributes = params[:child]
    @child.temporary = false

    @diagnostic = @child.diagnostics.build diag
    @diagnostic.child = @child
    @diagnostic.author = current_user
    answers.each { |a| @diagnostic.sign_answers.add(a) }

    if @child.save
      see_other [:wait, @child, @diagnostic]
    else
      render action: 'new'
    end
  end

  def temp
    Child.temporary.destroy_all
    if @data['photo']
      @child = Child.new @data.merge(temporary: true)
      display_updated @child.save
    else
      @child = Child.new
      display_updated true
    end
  end

  def edit
    if request.xhr?
      render partial: 'edit' if request.xhr?
    else
      render action: 'show'
    end
  end

  def update
    @child.skip_vaccination_validations!
    display_updated @child.update_attributes(@data)
    puts @child.errors
  end

  def destroy
    if @child.deletable_by? current_user
      @child.destroy
      see_other children_path
    else
      denied
    end
  end

  protected

  def rewrite_photo
    @data = data = params[:child]
    if data && data['photo'].is_a?(String)
      raw = data['photo']
      if raw.present?
        raw.tr! ' ', '+'
        sio = StringIO.new(Base64.decode64(raw))
        def sio.content_type; 'image/png'; end
        def sio.original_filename; 'hcam.png'; end
        data['photo'] = sio
      else
        data['photo'] = nil
      end
    end
    true
  end

  def display_updated success
    respond_to do |wants|
      wants.html do
        success ? redirect_to(:back) : render(action: :show)
      end
      wants.json do
        if success
          render json: { photo: @child.photo.url, present: @child.photo.present? }
        else
          render nothing: true, status: 422
        end
      end
    end
  end
end

app/helpers/children_helper.rb
# encoding: utf-8

module ChildrenHelper
  def bool_to_select val
    case val
    when true then 1
    when false then 0
    end
  end

  def village ch
    if ch.village
      ch.village.name
    elsif ch.village_name.present?
      "#{ch.village_name} (hors zone)"
    else
      '-'
    end
  end

  def zone_select_for_child ch
    Zone.csps.to_select.tap do |out|
      out << [
        "#{ch.village_name} (hors zone)",
        nil,
        { 'data-village' => ch.village_name, selected: true }] if ch.village_name.present?
      out << ['Hors zone', nil]
    end
  end

  def example_identifier
    if ch = Child.first
      ch.identifier
    else
      "ABCD-EFGH-JK"
    end
  end

  def form_gender val
    case val
    when true then '1'
    when false then '0'
    else ''
    end
  end

  def nee gender
    case gender
    when true then "Née"
    when false then "Né"
    else "Né/e"
    end
  end

  def vacc_class val
    case val
    when 0 then 'no'
    when 1 then 'yes'
    when 2 then 'dunno'
    else 'missing'
    end
  end
end

app/views/children/_edit.html.haml
- form_for @child do |form|
  = partial 'children/edit_fields', locals: { form: form }
  %button.edit(type="submit") Sauvegarder

app/views/children/_edit_fields.html.haml
%p.name
  %strong Nom :
  = form.text_field :last_name, 'data-label' => 'Nom', size: 30, class: 'required'
%p.name
  %strong Prénom :
  = form.text_field :first_name, 'data-label' => 'Prénom', size: 30, class: 'required'
%p.name
  %strong Nom de la mère :
  = form.text_field :mother, 'data-label' => 'Nom de la mère', size: 30, class: 'required'
%p.name
  %strong Sexe :
  = form.select :gender, [ [], %w(Masculin 1), %w(Féminin 0) ], { selected: form_gender(form.object.gender) }, class: 'required'
%p.name
  %strong
    %span.nee= nee form.object.gender
    le :
  = form.date_select(:born_on, :start_year => Date.today.year, :end_year => Date.today.year - 18, :include_blank => true)
%p.name
  %strong Village :
  = form.hidden_field :village_name
  = form.select :village_id, [ [], *zone_select_for_child(form.object) ], {}, class: 'required'
/ - if @child.new_record?
/   = form.fields_for :diagnostic, @diagnostic do |fields|
/     %p.name
/       %strong Distance :
/       = fields.select :distance, [ [], *Diagnostic::DISTANCES.to_select ], {}, class: 'required'

app/views/children/_edit_vaccinations.html.haml
%h3 Vérification de l’état vaccinal (cocher également les vaccins administrés ce jour) :
%table
  - child.form_vaccinations.each_slice(3) do |slice|
    %tr
      - for key, name in slice do
        %td= form.select key, [nil, 0, 1, 2], { selected: child.send(key) }, :class => 'boolean nullable negative'
        %th= form.label key, name

app/views/children/_measurements.html.haml
%table
  %tbody
    %tr
      %th(scope='row') Taille
      - if diagnostic.height.present?
        %td #{diagnostic.height.round(1)} cm
      - else
        %td -
      %th(scope='row') Temp.
      - if diagnostic.temperature.present?
        %td #{diagnostic.temperature.round(1)} °C
      - else
        %td -
    %tr
      %th(scope='row') Poids
      - if diagnostic.weight.present?
        %td #{diagnostic.weight.round(2)} kg
      - else
        %td -
      %th(scope='row') Périm. Brac.
      - if diagnostic.mac.present?
        %td{ class: class_for_mac(diagnostic.mac) } #{diagnostic.mac} mm
      - else
        %td -

app/views/children/_mugshot.html.haml
- klass = klass ? "#{klass} " : ''
- klass += @child.photo.present? ? 'present' : 'absent'
- method ||= :put
#mugshot.photo{:"data-field" => 'child[photo]', :"data-action" => action, :"data-method" => method, :class => klass}
  %div
    %img{alt: '', src: child.photo.url}
  %button(type="button") Supprimer

app/views/children/_profile.html.haml
.profile-child
  = partial 'children/mugshot', locals: { child: @child, action: child_path(@child) }
  %section
    .editable{'data-edit-href' => edit_child_path(@child)}
      = partial 'children/'+(show? ? 'show' : 'edit'), locals: { child: @child }
    .measurements
      %h2 Dernières mesures
      - if @child.last_visit
        = partial 'children/measurements', locals: { diagnostic: @child.last_visit }
        = partial 'diagnostics/indices', locals: { diagnostic: @child.last_visit }
      - else
        %p Never measured.
    .vaccinations
      %h3 Etat vaccinal :
      %table
        - @child.displayed_vaccinations.each_slice(3) do |slice|
          %tr
            - for key, name in slice
              %td{:class => vacc_class(@child.send(key))}= name

app/views/children/_show.html.haml
%span.name= child.sortable_name
%p
  %strong Identifiant :
  %span.identifier= child.identifier
  %br/
  - if child.mother.present?
    %strong Nom de la mère :
    = child.mother
    %br/

  %strong #{child.gender ? 'Né' : 'Née'} le :
  %span.age{'data-age' => child.age, 'data-months' => child.months, 'data-days' => child.days}
    #{l(child.born_on, :format => :long)}, #{months_to_text child.months}

  %br/
  %strong Village :
  = village child
  / - if child.last_visit
  /   %br/
  /   %strong Dernière distance :
  /   = child.last_visit.distance_name
- if Csps.point?
  %button.edit(type="button") Modifier

app/views/children/birthdate.html.haml
= form_for @child, html: { class: 'new child diagnostic' } do |form|
  = form.fields_for :diagnostic, @diagnostic do |fields|
    = partial 'diagnostics/edit_signs', locals: { form: fields }

app/views/children/index.html.haml
- unless params[:q]
  - content_for :header do
    %ul.menu
      - if current_user.admin?
        %li= link_to 'Stats', queries_path, :class => 'queries'
        %li= link_to 'Utilisateurs', users_path
        %li= link_to 'Mot de passe', password_users_path
        - if Zone.csps.root?
          %li= link_to 'Zones', zones_path, :class => 'syncs'
      - else
        %li= link_to 'Statistiques', queries_path, :class => 'queries'
        %li= link_to 'Changer mot de passe', password_users_path
      - if !Csps.point? && current_user.admin?
        %li
          = link_to syncs_path, :class => 'syncs' do
            Synchronisations
            - unless (unsynced = Zone.unsynced).zero?
              %strong= unsynced

- if params[:q]
  - content_for :breadcrumbs do
    %ul#breadcrumbs
      %li= link_to "Nouvelle Recherche", children_path
      %li Résultat de la recherche

%section
  - unless params[:name]
    %h1 Rechercher un patient
    %p.tip
      Un patient vient se présenter au
      %strong centre de santé.
      Veuillez tout d'abord rechercher son dossier afin de pouvoir remplir son
      %strong évaluation PCIME.
    - form_tag nil, method: 'get', class: 'search' do
      %div
        %label Nom et/ou prénom
        = text_field_tag :name
      %div
        %label Nom de la mère
        = text_field_tag :mother
      .select
        %label Naissance
        = select_tag :born, options_for_select((0..20).to_a.map {|y| [Date.today.year - y]*2}), :include_blank => 'Toutes les années'
      .select
        %label Village
        = select_tag :village, options_for_select(Zone.used_villages.to_select), include_blank: 'Tous les villages ou hors zone'
      %div
        %label Identifiant
        = text_field_tag :identifier, nil, placeholder: "Par exemple: #{example_identifier}"
      .buttons
        %button(type='submit') Rechercher

  - else
    %h1 Résultat de la recherche
    - if @error
      %p.error= @error
    - if @children.any?
      - paged = @children.includes(:village).paginate(@page, window: 15)
      %p.result-count
        - if paged.size < paged.total
          %strong= paged.size
          de
        %strong= paged.total
        patient(s) trouvé(s) pour les critères de recherches :
        = raw html_criteria @orig_name, @q
      %table.results
        %thead
          %tr
            %th!= sortable_header 'Nom', 'last_name'
            %th!= sortable_header 'Date de naissance', 'born_on'
            %th!= sortable_header 'Village', 'zone'
            %th!= sortable_header 'Dernière évaluation', 'last_visit_at'
            %th Dossier
        %tbody
          - for child in paged do
            - if child.born_on
              %tr{ :class => cycle("odd", "even") }
                %td
                  %strong= link_to child.sortable_name, child, title: "ID: #{child.identifier}\nMère: #{child.mother}"
                %td= child.born_on && l(child.born_on, :format => :long)
                %td= child.village ? child.village.name : "Hors zone: #{child.village_name}"
                %td= l child.last_visit_at.getlocal if child.last_visit_at
                %td= link_to "Voir le dossier →", child
      %ul.pagination
        - if paged.prev?
          %li.em= link_to "< Précédente", url_for(request.query_parameters.merge(:page => @page - 1))
        - 1.upto(paged.pages) do |p|
          - if p == @page
            %li= @page || 1
          - elsif (@page - p).abs < 4 || p == 1 || p == paged.pages
            %li= link_to p, url_for(request.query_parameters.merge(:page => p))
          - elsif (@page - p).abs < 5
            %li ...
        - if paged.next?
          %li.em= link_to "Suivante >", url_for(request.query_parameters.merge(:page => @page + 1))
      %nav.results
        %p
          Le patient n'est pas dans la liste ?
          - if Csps.point?
            = link_to 'Remplir sa première évaluation', new_child_path, :class => 'new-user-child-min'
            ou
          = link_to "Faire une nouvelle recherche", children_path, :class => 'new-search-min'
    - elsif params[:name]
      .no-result
        %p
          Aucun patient ne correspond aux critères de recherches :
          = raw html_criteria @orig_name, @q
        %nav
          - if Csps.point?
            = link_to 'Remplir sa première évaluation', new_child_path, :class => 'new-user-child'
            ou
          = link_to "Faire une nouvelle recherche", children_path, :class => 'new-search'

app/views/children/new.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche", children_path
    %li Nouveau Patient
= form_for @child, html: { class: 'new child diagnostic', 'data-questionnaire' => '/children/questionnaire' } do |form|
  .profile-child
    = partial 'mugshot', locals: { child: @child, action: temp_children_path, klass: 'editing', method: :post}
    %section
      %div.editable= partial 'edit_fields', locals: { form: form }
      = form.fields_for :diagnostic, @diagnostic do |fields|
        .measurements= partial 'diagnostics/edit_measurements', locals: { form: fields }
        .vaccinations= partial 'edit_vaccinations', locals: { form: form, child: @child }
      .warn{'data-condition' => 'data.enfant.age < 5'}
        L'âge de l'enfant doit être compris entre 0 et 59 mois.
      .next
        %button.next(type="button") Continuer
  .illnesses

  %section.other
    %h2 Autres problèmes de santé
    = form.fields_for :diagnostic, @diagnostic do |fields|
      = fields.text_area :other_problems, cols:20, rows:5

  %nav
    %button.validation(type="submit") Choisir les traitements

app/views/children/questionnaire.html.haml
= form_for @child, html: { class: 'new child diagnostic' } do |form|
  = form.fields_for :diagnostic, @diagnostic do |fields|
    .vaccinations= partial 'edit_vaccinations', locals: { form: form, child: @child }
    = partial 'diagnostics/edit_signs', locals: { form: fields }

app/views/children/show.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Nouvelle Recherche", children_path
    %li= @child.sortable_name

= partial 'children/profile'

%nav.child
  - if @child.deletable_by? current_user
    - form_tag child_path(@child), method: 'delete' do
      %button.confirm.delete(type="submit" data-confirm="Etes vous sûr de vouloir supprimer cet enfant ?") Supprimer
  - if Csps.point? && @child.of_valid_age?
    = link_to 'Nouvelle consultation', new_child_diagnostic_path(@child), :class => 'new-diagnostic'
    - if @child.diagnostics.any?
      = link_to 'Consultation de suivi', new_child_diagnostic_path(@child, kind: 'follow'), :class => 'follow-diagnostic'

%h2.em Liste des évaluations

%section.list-arrow
  %ul
    - for diag in @child.diagnostics.order('id DESC').limit(5) do
      %li{ :class => cycle("odd", "even") }= partial 'diagnostics/header', locals: { diagnostic: diag }