config/routes.rb
Csps::Application.routes.draw do
  resource :session, controller: 'session' do
    get :welcome, :restore
  end
  resource :syncs
  resources :zones
  resources :users do
    get :logins, on: :member, to: :user_logins
    get :logins, :password, on: :collection
  end
  resources :queries do
    get :export, on: :member
  end

  resources :illnesses do
    post :classification, on: :member
  end

  resources :children do
    collection do
      get :calculations, :questionnaire
      post :temp
    end
    member do
      get :indices
    end
    resources :diagnostics do
      collection do
        get :questionnaire
      end
      member do
        get :treatments, :wait
        post :calculations
      end
    end
  end

  root to: 'children#index'
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include Csps::Exportable
  attr_reader :password, :password_confirmation

  globally_has_many :diagnostics, as: :author
  has_many :events

  before_validation do
    self.name = name.strip.gsub(/\s+/, ' ') if name.present?
  end

  validates_presence_of :name
  validates_presence_of :password, :on => :create
  validates_presence_of :password_confirmation, :if => :password
  validates_confirmation_of :password, :if => :password
  validates_uniqueness_of :name, scope: :zone_id
  before_save :crypt_password

  scope :admins, :conditions => ['admin_at IS NOT NULL AND admin_at <= ?', Time.now]
  scope :local, ->() { Zone.csps ? where(zone_id: Zone.csps.id) : where(id: 0) }

  def password= pwd; @password = pwd if pwd.present?; end
  def password_confirmation= pwd; @password_confirmation = pwd if pwd.present?; end

  def self.authenticate user_id, password
    if Csps.site
      (u = find_by_id_and_zone_id(user_id, Zone.csps.id)) &&
      u.authenticate(password) &&
      u
    end
  end

  def deletable_by? user
    user.admin? && super
  end

  def authenticate password
    BCrypt::Password.new(crypted_password) == password
  end

  def self.to_login_select
    select('id, name').map { |u| [ u.id, u.name ] }
  end

  def password_expired?
    password_expired_at && password_expired_at < Time.now
  end

  def admin
    admin_at.present?
  end
  alias admin? admin
  def admin_was
    admin_at_was && admin_at_was <= updated_at_was
  end
  alias was_admin? admin_was
  def admin= value
    if value && value != 'false' && value != '0'
      self.admin_at = Time.now.utc unless admin
      true
    else
      self.admin_at = nil
      false
    end
  end

  protected

  def crypt_password
    self.crypted_password = BCrypt::Password.create password if password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  admin_required except: [:create, :password, :update]
  login_required only: [:password, :update], expire: false

  before_filter :admin_or_first_run, only: :create
  before_filter :paged, only: [ :logins, :user_logins ]

  fetch 'User', also: [ :user_logins ]

  layout :decide_layout

  def index
    back 'Rechercher un patient', children_path
    @users = User.order('admin_at DESC, name ASC')
    @logins = Event.logins.history.joins(:user).limit(10)
  end

  def new
    back 'Retour', users_path
    @user = User.new
  end

  def create
    restore = User.count.zero? && params[:restore].present?
    @user = User.new params[:user]
    if Csps.site.blank?
      if params[:zone_id] && zone = Zone.find(params[:zone_id])
        zone.occupy! restore
      else
        @user.errors[:base] << :no_site
      end
    end

    if User.count.zero?
      @user.admin = true
    else
      @user.password_expired_at = Time.now
    end

    return see_other('/session/restore') if restore

    if @user.save
      if !logged_in? && @user.admin
        persist_user_into_session @user
        see_other children_path
      else
        see_other users_path
      end
    elsif Csps.site
      render action: 'new'
    else
      render template: 'session/welcome'
    end
  end

  def edit
    back 'Retour', users_path
  end

  def update
    if @user.password_expired? && @user != current_user
      return see_other('/user/password')
    end

    data = params[:user]
    pw = !!params[:pwchange]

    unless admin?
      return denied if @user != current_user
      data = data.keep %w(password password_confirmation)
    end

    if @user == current_user && data['password'].present?
      unless @user.authenticate(params[:password])
        @pw_error = true
        return render(action: (pw ? 'password' : 'edit'))
      end
      data[:password_expired_at] = nil
    end

    if @user.update_attributes data
      if pw
        see_other session.delete(:after_change) || '/'
      else
        see_other users_path
      end
    else
      render(action: (pw ? 'password' : 'edit'))
    end
  end

  def destroy
    if @user != current_user && @user.diagnostics.empty?
      @user.destroy
    end
    see_other users_path
  end

  def logins
    @logins = Event.logins.history.joins(:user)
  end

  def user_logins
    @logins = @user.events.logins.history
  end

  def password
  end

  protected

  def paged
    @page = (params[:page] || '1').to_i
  end

  def logged_in_or_first_run
    User.count.zero? || logged_in? || denied
  end

  def admin_or_first_run
    User.count.zero? || (logged_in? and admin?) || denied
  end

  def decide_layout
    logged_in? ? 'application' : 'lobby'
  end
end

app/views/users/_form.html.haml
%div
  %label Prénom et Nom
  = form.text_field :name
  = errors_on form, :name
%div
  %label Mot de passe
  = form.password_field :password, :value => ''
  = errors_on form, :password
%div
  %label Confirmer mot de passe
  = form.password_field :password_confirmation, :value => ''
  = errors_on form, :password_confirmation
- if logged_in? and admin? and form.object != current_user
  %div
    %label Administrateur
    = form.select :admin, [ nil, 0, 1 ], {:selected => (form.object.admin? ? 1 : 0) }, :class => :boolean
    = errors_on form, :admin

app/views/users/_logins.html.haml
%table.results.users
  %thead
    %tr
      %th Nom
      %th Connecté(e) à
  %tbody
    - for ev in logins do
      %tr.remote
        %td= link_to ev.user.name, [ :logins, ev.user ]
        %td= l(ev.created_at.getlocal)

app/views/users/_new.html.haml
- form_for @user, html: { :'data-admin-confirm' => "Vous ne serez plus administrateur après la première connexion du nouvel administrateur.\n\nVoulez-vous continuer ?" } do |f|
  = partial 'users/form', locals: { form: f }
  %div
    %button(type="submit") Créer

app/views/users/edit.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li= link_to "Utilisateurs", users_path
    %li= @user.name

.welcome
  %h1 Editer le profil
  %p 
    C'est ici que vous pouvez modifier les 
    %br 
    renseignements de votre compte.
  - form_for @user, html: { :'data-admin-confirm' => "Vous ne serez plus administrateur après la première connexion du nouvel administrateur.\n\nVoulez-vous continuer ?" } do |f|
    = partial 'form', locals: { form: f }
    %div
      %button(type="submit") Modifier

app/views/users/index.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li Utilisateurs

%nav= link_to 'Nouvel utilisateur', new_user_path, :class => 'new-user'

%section
  %h1 Utilisateurs de ce CSCOM
  %table.results.users
    %thead
      %tr
        %th Nom
        %th Administrateur
        %th
    %tbody
      - for user in @users.where(zone_id: Zone.csps.id) do
        %tr.local
          %td= link_to user.name, [ :edit, user ]
          %td= user.admin? ? 'Oui' : 'Non'
          %td
            - if user != current_user && user.diagnostics.empty?
              - form_for user, html: { :method => :delete, :class => 'confirm', 'data-confirm' => "Supprimer #{user.name} ?" } do
                %button{type: 'submit'} Supprimer
            - else
              Non autorisé à supprimer

- if @logins.any?
  %section
    %h1 Dernières connexions
    = render partial: 'logins', locals: { logins: @logins }
    %p.next
      = link_to 'Toutes les connexions', logins_users_path

- if (others = @users.where('zone_id != ?', Zone.csps.id)).any?
  %section
    %h1 Utilisateurs d'autres CSCOM
    %table.results.users
      %thead
        %tr
          %th Nom
          %th Administrateur
          %th
      %tbody
        - for user in others
          %tr.remote
            %td= user.name
            %td= user.admin? ? 'Oui' : 'Non'
            %td Non autorisé à supprimer

app/views/users/logins.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li= link_to 'Utilisateurs', '/users'
    %li Dernières connexions 

%section
  %h1 Dernières connexions
  - if @logins.any?
    - paged = @logins.paginate @page, window: 15

    = render partial: 'logins', locals: { logins: paged }

    %ul.pagination
      - if paged.prev?
        %li.em= link_to "< Précédente", url_for(request.query_parameters.merge(:page => @page - 1))
      - 1.upto(paged.pages) do |p|
        - if p == @page
          %li= @page || 1
        - elsif (@page - p).abs < 4 || p == 1 || p == paged.pages 
          %li= link_to p, url_for(request.query_parameters.merge(:page => p))
        - elsif (@page - p).abs < 5
          %li ...
      - if paged.next?
        %li.em= link_to "Suivante >", url_for(request.query_parameters.merge(:page => @page + 1))
  - else
    %p Aucune connexion.

app/views/users/new.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li= link_to "Utilisateurs", users_path
    %li Nouvel Utilisateur

.welcome
  %h1 Nouvel utilisateur
  = partial 'new'

app/views/users/password.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li Mot de passe

- user = @user || current_user
.welcome
  - if current_user.password_expired?
    %h1 Personnalisez votre mot de passe
  - else
    %h1 Changement de mot de passe

  - form_for user do |form|
    %input(type="hidden" name="pwchange" value="1")
    %div
      %label Mot de passe actuel
      %input{type: 'password', name: 'password'}
      - if @pw_error
        .errors Mot de passe incorrect
    %div
      %label Nouveau mot de passe
      = form.password_field :password, :value => ''
      = errors_on form, :password
    %div
      %label Confirmer mot de passe
      = form.password_field :password_confirmation, :value => ''
      = errors_on form, :password_confirmation
    %div
      %button(type="submit") Modifier

app/views/users/user_logins.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li= link_to 'Utilisateurs', '/users'
    %li Dernières connexions

%section
  %h1 Dernières connexions de #{@user.name}
  - if @logins.any?
    - paged = @logins.paginate @page, window: 15
    = render partial: 'logins', locals: { logins: paged }

    %ul.pagination
      - if paged.prev?
        %li.em= link_to "< Précédente", url_for(request.query_parameters.merge(:page => @page - 1))
      - 1.upto(paged.pages) do |p|
        - if p == @page
          %li= @page || 1
        - elsif (@page - p).abs < 4 || p == 1 || p == paged.pages
          %li= link_to p, url_for(request.query_parameters.merge(:page => p))
        - elsif (@page - p).abs < 5
          %li ...
      - if paged.next?
        %li.em= link_to "Suivante >", url_for(request.query_parameters.merge(:page => @page + 1))
  - else
    %p Aucune connexion.