config/routes.rb
Csps::Application.routes.draw do
  resource :session, controller: 'session' do
    get :welcome, :restore
  end
  resource :syncs
  resources :zones
  resources :users do
    get :logins, on: :member, to: :user_logins
    get :logins, :password, on: :collection
  end
  resources :queries do
    get :export, on: :member
  end

  resources :illnesses do
    post :classification, on: :member
  end

  resources :children do
    collection do
      get :calculations, :questionnaire
      post :temp
    end
    member do
      get :indices
    end
    resources :diagnostics do
      collection do
        get :questionnaire
      end
      member do
        get :treatments, :wait
        post :calculations
      end
    end
  end

  root to: 'children#index'
end

app/models/query.rb
require 'json'

class Query < ActiveRecord::Base
  # These correspond to diag kinds "first", "initial" and "follow" in this order.
  enum :case_status, %w{first initial follow new old}
  CASE_STATUSES.each.with_index { |n,i| const_set n.upcase, i }

  AGE = {
    'SQLite' => ->(ref, age) { "date(#{ref}, '-#{age} months')" },
    'PostgreSQL' => ->(ref, age) { "(#{ref} - interval '#{age} months')" }}
  DAYS = {
    'SQLite' => ->(ref, age) { "date(#{ref}, '-#{age} days')" },
    'PostgreSQL' => ->(ref, age) { "(#{ref} - interval '#{age} days')" }}

  validates_presence_of :title, :klass

  def run
    k, ca = klass.constantize, connection.adapter_name
    aref = k.age_reference_field
    rel = case_status ? k.where(kind: case_status) : k

    rel = case case_status
      when NEW              then k.where('kind IN (?)', [FIRST, INITIAL])
      when OLD              then k.where('kind IN (?)', [INITIAL, FOLLOW])
      when FIRST..FOLLOW    then k.where(kind: case_status)
      else k
    end

    for cond in Array(YAML.load(conditions))
      rel = case cond['type']
        when 'age'
          rel.where "#{AGE[ca].(aref, cond['value'].to_i)} #{cond['operator']} #{k.table_name}.born_on"
        when 'days'
          rel.where "#{DAYS[ca].(aref, cond['value'].to_i)} #{cond['operator']} #{k.table_name}.born_on"
        when 'field', 'boolean'
          att, val = k.rewrite_query_conditions cond
          op = (cond['type'] == 'boolean') ? '=' : cond['operator']

          path = att.split '.'
          inkl, model, field = nil, k, path.pop
          path.each do |i|
            i = i.intern
            model = model.reflections[i].klass
            inkl = build_include_hash inkl, i
          end

          rel = rel.includes(inkl) if inkl
          rel.where("#{model.table_name}.#{field} #{op} ?", val)
        when 'sign'
          raise "Sign is only supported by Diagnostic" if k != Diagnostic
          sign = Sign.find_by_key cond['sign']
          rel.where(
            "uqid IN (
              SELECT diagnostic_uqid FROM sign_answers
              WHERE sign_id=? AND #{sign.answer_class.field} #{cond['operator']} ?)", sign.id, cond['value'])
      end
    end

    results = rel.group(:month).count(distinct && "DISTINCT #{distinct}").tap do |h|
      h.keys.each do |k|
        s = k.to_s
        h.store "#{s[0,4]}/#{s[4,2]}", h.delete(k)
      end
    end
    fill_in_gaps results
  ensure
    update_attribute :last_run_at, Time.now
  end

  def self.latest_run limit=4
    all(:order => 'last_run_at DESC', :limit => limit, :conditions => ['last_run_at IS NOT NULL'])
  end

  protected

  def fill_in_gaps data
    return data if data.blank?

    ks = data.keys.sort
    time = Time.parse ks.first
    finish = Time.parse ks.last
    while time < finish do
      key = time.strftime('%Y/%m')
      data[key] ||= 0
      time += 1.month
    end
    data
  end

  def build_include_hash incl, n
    case incl
      when nil then n
      when Symbol then { incl => n }
      when Hash
        key, value = incl.first
        { key => build_include_hash(value, n) }
    end
  end
end

app/controllers/queries_controller.rb
require 'json'

class QueriesController < ApplicationController
  login_required
  fetch 'Query'
  helper Ziya::HtmlHelpers::Charts
  helper Wopata::Ziya::HtmlHelpersFix

  require "spreadsheet/excel" 
  
  def index
    back 'Rechercher un patient', children_path
  end

  def show
    back 'Afficher une autre statistique', queries_path
    @query = Query.find(params[:id])
    @results = @query.run
    respond_to do |format|
      format.html
      format.xml do
        if @results.any?
          chart = Ziya::Charts::Column.new
          chart.add :theme, 'pimp'
          labels = @results.keys.sort
          labels = labels.map { |k| k[-2..-1] == '01' ? k[0..3] : '' } if labels.size > 12
          chart.add :axis_category_text, labels
          chart.add :series, '', @results.keys.sort.map { |k| @results[k] }
          render xml: chart.to_xml
        else
          render nothing: true
        end
      end
    end
  end
end

app/views/queries/_table_report.html.haml
- start_column = 2
%table
  %tr
    %td
      ' '
    %td
      "Cases"
time_series.each_with_index do |ts, i|

  sheet1[i+1, 0] = ts
end

report.each_with_index do |rp, j|
  sheet1[j+1, 1] = rp[:value]
end

app/views/queries/index.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li Statistiques

- queries = Query.order(:id).select('group_title, min(id) AS id').group(:group_title)

%section.illness.list-arrow
  %h2 #{Query.count} statistiques
  %ul
    - queries.each do |q|
      %li.query{ :class => cycle("odd", "even") }
        = link_to query_path(q) do
          = q.group_title
          %span= "(#{Query.where(group_title: q.group_title).count} statistiques)"

app/views/queries/show.html.haml
- content_for :breadcrumbs do
  %ul#breadcrumbs
    %li= link_to "Recherche Patient", children_path
    %li= link_to "Statistiques", queries_path
    %li= @query.group_title

%section
  %h1
    = @query.group_title

  - if group_title = @query.group_title
    .query-selector
      %form
        %select.autolink{ data: { url: 'queries/' } }
          - Query.where(group_title: group_title).each do |q|
            %option{ value: q.id, selected: q == @query }= q.title

  - if @results.any?
    %h2= @query.title
    %div.query-graph!= ziya_chart query_url(@query, format: :xml), size: '1200x300'
    %table.results
      %thead
        %tr
          %th{:colspan => 4}
            Valeurs
      %tbody
        - @results.keys.sort.reverse.each do |k|
          %tr{ :class => cycle("odd", "even") }
            %td= k
            %td= @results[k]
  - else
    %p Pas de données affichables